// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"
)

type Chirp struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Body      string
	UserID    string
}

type User struct {
	ID             string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
}
